name: Calling workflow ci-pr-checks for verifying title, code and image in PR

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: write
  issues: write
  repository-projects: read

jobs:
  run-pr-checks:
    uses: felleslosninger/github-workflows/.github/workflows/ci-pr-checks.yml@main
    with:
      application-type: spring-boot
      java-version: 21
      pull-request-title: ${{ github.event.pull_request.title }}
      pull-request-allowed-prefixes: "MOVE-,Bump,PF-"
      enable-auto-merge-dependabot: true
      auto-merge-types: "version-update:semver-patch;version-update:semver-minor"
      enable-trivy-image-scan: false
    secrets: inherit
